spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=BatteryPlus;integratedSecurity=false;encrypt=true;trustServerCertificate=true
    username: sa
    password: sql
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      poolName: HikariBatteryPlusDev
      max-lifetime: 2000000
      connection-timeout: 30000
    jpa:
      database-platform: org.hibernate.dialect.SQLServer2012Dialect
      hibernate:
        naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql: true
          use_sql_comments: true
          
logging:
  level:
    org:
      hibernate:
        type: trace
